config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "profile", to: "pages#profile"
  get "user_items", to: "pages#user_items"

  get "up" => "rails/health#show", as: :rails_health_check

  resources :items do
    collection do
      get :top
      get :bottom
      get :shoes
    end
  end
  resources :movements, only: %i[show index]
  post "movements", to: "movements#create", as: :buy
  patch "sold", to: "movements#sold"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_one :movement
  has_one_attached :photo

  validates :name, presence: true
  validates :price, presence: true
  validates :genre, presence: true, inclusion: { in: %w(men women) }
  validates :size, presence: true, inclusion: { in: %w(s m l xl) }
  validates :color, presence: true
  validates :kind, presence: true, inclusion: { in: %w(top bottom shoes) }
  validates :photo, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_attribute,
  against: [ :kind, :size, :genre],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/movement.rb
class Movement < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :items
  has_many :movements
  has_many :items, through: :movements
  # me trae un array de todas las compras del usuario
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: %i[show edit update destroy]
  def index
    @items = Item.all
    if params[:query].present?
      @items = Item.search_by_attribute(params[:query])
    end
  end
  
  def show
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if item.save
      redirect_to items_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @item.update(item_params)
  end

  def destroy
    @item.destroy
    redirect_to items_path
  end

  private

  def find_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:price, :size, :genre, :color, :status, :type, :name, :photo)
  end
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  before_action :set_item, only: %i[show create]
  before_action :authenticate_user!, only: %i[index show create]

  def index
    #@movements = Movement.where(user_id: current_user.id)
    @movements = Movement.all
  end

  def show
    @movement = Movement.find(params[:id])
  end

  def create
    @movement = Movement.create(purchase_date: Date.today, user_id: current_user.id, item_id: params[:item_id])
    sold(@item)
    redirect_to(items_path)
  end

  def sold(item)
    item.update_attribute(:status, "sold")
  end

  private

  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: :profile
  def home
    @items = Item.all
  end

  def profile
  end
  def user_items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_form.html.erb
<div class="container">
  <hr>
  <div class="item_form">
  <p class= "text-danger">* required field</p>
    <%= simple_form_for(@item) do |f| %>
    <%= f.input :name, placeholder: "Referencia de la prenda" %>
    <%= f.input :price, placeholder: "$" %>
    <%= f.input :genre, placeholder: "men or women" %>
    <%= f.input :size, placeholder: "s, m, l, xl" %>
    <%= f.input :color, placeholder: "red, yellow, white." %>
    <%= f.input :kind, placeholder: "top bottom shoes" %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
  </div>
</div>

app/views/items/_list.html.erb
      <% @items.each do |item| %>
<div>
  <div class="row row-cols-sm-1 row-cols-md-2 row-cols-lg-4" >
    <div class="col">
        <div class="card">
          <div class="card-img-top">
            <%= cl_image_tag item.photo.key, height: 250, width: 300, crop: :fill %>
          </div>
          <div class="card-body" >
            <h5 class="card-title"><%= item.name %>, Price: $<%= item.price.floor(2) %></h5>
            <p class="btn"><%= link_to "See details", item_path(item.id)%></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/items/bottom.html.erb
<h1>Clothes for bottom</h1>
<div>
<%= link_to "Back to all products", items_path %>
<%= render "list", items: @items %>
</div>

app/views/items/edit.html.erb
<div class="index-header" style="background-image: linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7)), url(https://t3.ftcdn.net/jpg/01/38/94/62/360_F_138946263_EtW7xPuHRJSfyl4rU2WeWmApJFYM0B84.jpg);">
  <div class="header">
    <h1>Edit your item</h1>
  </div>
    <div class="d-flex justify-content-center mt-3">
 <%= link_to "Back to profile", profile_path, class: "btn btn-ghost" %>
</div>


<%= render "form", item: @item %>

app/views/items/index.html.erb
<div class="index-header" style="background-image: linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7)), url(https://t3.ftcdn.net/jpg/01/38/94/62/360_F_138946263_EtW7xPuHRJSfyl4rU2WeWmApJFYM0B84.jpg);">
  <div class="header">
    <h1>Clothes</h1>
  </div>
    <div class="d-flex justify-content-center mt-3">
      <%= link_to "Go back", root_path, class: "btn btn-ghost" %>
    </div>
</div>


<div class="container" style="display: flex; ">



  <div class="sidenav" style=" font-size: 20px;" >
    <%= link_to "Tops", items_path(query: "top") %>
    <%= link_to "Bottoms", items_path(query: "bottom") %>
    <%= link_to "Shoes", items_path(query: "shoes") %>
  </div>

  <div class="main-containter" style="margin-left: 100px;" >
    <div class="index-flexbox">
      <% @items.each do |item| %>
          <div class="card" style="width: 15rem; border-radius: 10px;   box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); ">
            <%= cl_image_tag item.photo.key, class:"card-img-top card-product-img br-10px" %>
            <div class="card-body">
              <h4 style="font-weight: bolder;"><%= item.name %></h4>
              <strong><p>Price: $<%= item.price.floor(2) %></p></strong>
              <p>Kind of item: <%= item.kind %></p>
              <p class="btn btn-primary" style="box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)" ><%= link_to "See details", item_path(item.id), class:"link-light br-1px text-decoration-none"%></p>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="index-header" style="background-image: linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7)), url(https://t3.ftcdn.net/jpg/01/38/94/62/360_F_138946263_EtW7xPuHRJSfyl4rU2WeWmApJFYM0B84.jpg);">
  <div class="header">
    <h1>Sell your item</h1>
  </div>
    <div class="d-flex justify-content-center mt-3">
   <%= link_to "Back to profile", profile_path, class: "btn btn-ghost" %>
</div>




<%= render "form", item: @item %>

app/views/items/shoes.html.erb
<h1>Clothes for shoes</h1>
<div>
<%= link_to "Back to all products", items_path %>
<%= render "list", items: @items %>
</div>

app/views/items/show.html.erb
<div class="index-header" style="background-image: linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7)), url(https://media.istockphoto.com/id/941051278/photo/close-up-of-woman-hand-choosing-thrift-young-and-discount-t-shirt-clothes-in-store-searching.webp?b=1&s=612x612&w=0&k=20&c=PfKTXNCoyzCfsk6cciizsUYsRB04-zxXkV8-3XjLYtY=);">
  <div class="header">
    <h1>This Item</h1>
  </div>
</div>

<div class="card-product">
  <div class="img"><%= cl_image_tag @item.photo.key, crop: :fill %></div>
  <div class="card-product-infos">
    <h2><%=@item.name%> <br><strong>$<%=@item.price.floor(2)%> USD</strong></h2>
    <p><%=@item.kind.capitalize%></p>
    <p>Size: <%=(@item.size).upcase%></p>
    <p>For <%=(@item.genre).capitalize%></p>
    <p>Status: <%=@item.status%></p>
    <p>Seller: <%=@item.user.first_name%> <%=@item.user.last_name%></p>
    <p>Phone number: <%=@item.user.phone_number%></p>

        <div style="margin-top: 10px;">
          <%= button_to "Buy this item", buy_path(item_id: @item.id), class: "btn btn-primary ", data: {turbo_confirm: "Thank you for buying this item!"}%>
        </div>
        <div style="margin-top: 10px;">
          <%= link_to "Back to all items", items_path, class: "btn btn-primary" %>
        </div>
  </div>
</div>

app/views/items/top.html.erb
<h1>Clothes for top</h1>
<div>
<%= link_to "Back to all products", items_path %>
<%= render "list", items: @items %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arropa2</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "shared/navbar"%>
    <div id="page-container">
    <div id="content-wrap">
    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    </div>
    <%= render "shared/footer"%>
    </div>
  </body>
</html>

app/views/movements/index.html.erb
<div class="index-header" style="background-image: linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7)), url(https://t3.ftcdn.net/jpg/01/38/94/62/360_F_138946263_EtW7xPuHRJSfyl4rU2WeWmApJFYM0B84.jpg);">
  <div class="header">
    <h1 style="font-weight:bolder; padding: 15px; margin-top: 20px; "><%= current_user.first_name %>'s movements</h1>
  </div>
    <div class="d-flex justify-content-center mt-3">
 <%= link_to "Back to profile", profile_path, class: "btn btn-ghost" %>
</div>
</div>





<div class="containter" style="display: flex;  padding-bottom: 45px;">


    <div class="flex" style="display: flex; margin-top: 20px; margin-bottom: 35px;">
        <div class="card" style="width: 18rem;">
          <div class="card-header">
            <h3>Bought Items</h3>
          </div>
        <ul class="list-group list-group-flush">
          <% current_user.movements.each do |compra| %>
          <li class="list-group-item"><h4><%= compra.item.name%></h4><p>On:<%= compra.purchase_date%></p></li>
          <% end %>
        </ul>
      </div>

      <div class="card" style="width: 18rem;">
        <div class="card-header">
          <h3>Sold Items</h3>
        </div>
        <ul class="list-group list-group-flush">
          <% @movements.each do |movimiento|%>
            <% item = movimiento.item %>
              <% if item.user_id == current_user.id %>
              <li class="list-group-item"><h4><%= item.name %></h4></li>
              <% end %>
            <% end %>
        </ul>
      </div>

    </div>



<!-- <% @movements.each do |venta| %>
<p><%= venta.item.user.first_name %></p>
<p><%= venta.purchase_date %></p>
<% end %> -->

app/views/movements/show.html.erb
<h2><%= current_user.first_name %>'s movements</h2>
<h3>Bought</h3>

<% current_user.movements.each do |compra| %>
<!--<p><%= compra.item_id%></p> -->
<h4><%= compra.item.name%></h4>
<p>On:<%= compra.purchase_date%></p>
<% end %>

<p>Sold</p>

<!-- <% @movements.each do |venta| %>
<p><%= venta.item.user.first_name %></p>
<p><%= venta.purchase_date %></p>
<% end %> -->

<% @movements.each do |movimiento|%>
<% item = movimiento.item %>
<% if item.user_id == current_user.id %>
<h4><%= item.name %></h4>
<p>On:<%= item.purchase_date%></p>
<% end %>
<% end %>

app/views/pages/home.html.erb
<!--          *******************************************         START      BANNER         -->

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1562740672-22db5c969f04?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cm9wYXxlbnwwfDB8MHx8fDA%3D);">
  <div class="container"   >
    <h1>ARROPA2 <strong>buy &</strong> sell <strong> your CLOTHES</strong>!</h1>
    <p>Give your garments a second chance around!</p>
    <%= link_to "View products", items_path, class: "btn btn-warning br-1px " %>
  </div>
</div>


<!--          *******************************************         END    BANNER         -->


<!--          *******************************************          START      CARDS         -->

  <div class="row row-cols-1 row-cols-md-3 g-4" style="margin: 40px;">
    <div class="col">
    <div class="card h-100" style="border-radius: 10px;   box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
        <img src="https://images.unsplash.com/photo-1523381294911-8d3cead13475?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="card-img-top" style="height: 20; width: 20;" alt="t-shirt">
        <div class="card-body">
          <h5 class="card-title">Tops</h5>
          <p class="card-text">Garments as t-shirts, shirts, tops and blouses.</p>
            <%= link_to "View", items_path(query: "top"), class: "btn btn-primary" %>
        </div>
    </div>
  </div>
    <div class="col">
      <div class="card h-100" style="border-radius: 10px;   box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
        <img src="https://images.unsplash.com/photo-1576995853123-5a10305d93c0?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" style="height: 20; width: 20;" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Bottoms</h5>
          <p class="card-text">Trousers, pants, shorts, skirts, you name it!</p>
            <%= link_to "View", items_path(query: "bottom"), class: "btn btn-primary"  %>
        </div>
    </div>
  </div>
    <div class="col">
      <div class="card h-100" style="border-radius: 10px;   box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
        <img src="https://plus.unsplash.com/premium_photo-1661780784016-84df03d7d8a8?q=80&w=1506&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" style="height: 20; width: 20;" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">Shoes</h5>
          <p class="card-text">Get your sneakers, boots, high-heels or combatboots here!</p>
            <%= link_to "View", items_path(query: "shoes"), class: "btn btn-primary"%>
        </div>
    </div>
  </div>




 </div>




<!--          *******************************************         END CARDS        -->

app/views/pages/profile.html.erb
<div class="index-header" style="background-image: linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7)), url(https://t3.ftcdn.net/jpg/01/38/94/62/360_F_138946263_EtW7xPuHRJSfyl4rU2WeWmApJFYM0B84.jpg);">
  <div class="header">
    <h1>Profile</h1>
  </div>
    <div class="d-flex justify-content-center mt-3">
      <%= link_to "Home", root_path, class: "btn btn-ghost" %>
    </div>
</div>




<div class="profile-info">
  <div class="d-flex justify-content-center align-items-center p-5">
  <div class="card" style="width: 18rem;">
    <div class="card-header">
      <h2 class="text-center"><%= current_user.first_name %>'s profile</h2>
    </div>
    <div class="mt-2 ps-3">
      <ul class="list-unstyled">
        <li><%= current_user.email %></li>
        <li><%= current_user.first_name %> <%= current_user.last_name %></li>
        <li><%= current_user.phone_number %></li>
        <li><%= current_user.address %></li>
      </ul>
    </div>
  </div>
</div>
<div class="d-flex justify-content-center">
    <ul class="list-group list-group-flush text-decoration-none text-center list-unstyled">
      <li class="p-2"><%= link_to "Sell clothes", new_item_path, class: "btn btn-primary mt-20px" %></li>
      <li class="p-2" ><%= link_to "My movements", movements_path, class: "btn btn-primary mt-20px" %></li>
      <li class="p-2" ><%= link_to "My items", user_items_path,class: "btn btn-primary mt-20px" %></li>
    </ul>
</div>
</div>

app/views/pages/user_items.html.erb
<div class="index-header" style="background-image: linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7)), url(https://t3.ftcdn.net/jpg/01/38/94/62/360_F_138946263_EtW7xPuHRJSfyl4rU2WeWmApJFYM0B84.jpg);">
  <div class="header">
    <h1>My Items</h1>
  </div>
    <div class="d-flex justify-content-center mt-3">
      <%= link_to "My Profile", profile_path, class: "btn btn-ghost" %>
    </div>
</div>





  <div class="main-containter" style="margin-left: 100px;" >
    <div class="index-flexbox">
      <% @items.each do |item| %>
          <div class="card" style="width: 15rem; border-radius: 10px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19); ">
            <%= cl_image_tag item.photo.key, class:"card-img-top card-product-img br-10px" %>
            <div class="card-body">
              <h4 style="font-weight: bolder;"><%= item.name %></h4>
              <strong><p>Price: $<%= item.price.floor(2) %></p></strong>
              <p>Kind of item: <%= item.kind %></p>
              <p>Size: <%=(item.size).upcase%></p>
              <p>For <%=(item.genre).capitalize%></p>
              <p>Seller: <%=item.user.first_name%> <%=item.user.last_name%></p>
              <p>Phone number: <%=item.user.phone_number%></p>

               <div style="margin-top: 10px;">
                <%= link_to "Edit", edit_item_path(item.id), class: "btn btn-primary "  %>
              </div>
              <div style="margin-top: 10px;">
                <%= link_to "Delete", item_path(item.id), class: "btn btn-danger text-light", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
              </div>



            </div>
          </div>
        <% end %>
    </div>
  </div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links d-flex justify-content-center pt-2 fs-5">
    <a href="#"><i class="fab fa-github text-secondary pe-2"></i></a>
    <a href="#"><i class="fab fa-instagram text-secondary pe-2"></i></a>
    <a href="#"><i class="fab fa-facebook text-secondary pe-2"></i></a>
    <a href="#"><i class="fab fa-twitter text-secondary"></i></a>
    <a href="#"><i class="fab fa-linkedin text-secondary ps-2"></i></a>
  </div>
  <div class="fs-6 footer-copyright pt-3 d-flex justify-content-center text-center">
    <h6>Arropa2 is made with <i class="fas fa-heart text-danger"></i> at Le Wagon. <BR>ALLRIGHTSRESERVED 2023.DONTCOPY<br><span>Beyda, Victoria & Luis Camilo</span></h6>
  </div>
</div>

app/views/shared/_navbar.html.erb
    <!--          *******************************************          START    NAVBAR         -->

    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon ">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Clothes_hanger_icon_3.svg/800px-Clothes_hanger_icon_3.svg.png?20150106164522" %>
    <% end %>

    <button class="navbar-toggler" type="button"  data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Buy", items_path, class: "nav-link" %>
            <li class="nav-item">
              <%= link_to "Sell", new_item_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Profile", profile_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, class: "btn btn-primary br-1px", data: {turbo_method: :delete} %>
            </li>
          <li class="nav-item dropdown">
          <!-- <%= image_tag "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Clothes_hanger_icon_3.svg/800px-Clothes_hanger_icon_3.svg.png?20150106164522", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %> -->
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<!--          *******************************************                END NAVBAR       -->